language: php

php:
  - 5.6

services:
  - mongodb

install:
  - echo y | pecl install mongo

before_script: phpenv config-add travisconfig.ini

script: phpunit --bootstrap src/Script/verificaCaracteristica.php teste/script/verificaCaracteristicaTest.php