language: php

php:
  - 5.6

services:
  - mongodb

install:
  - echo y | pecl install mongo

before_script: phpenv config-add travisconfig.ini

script:
  - phpunit --bootstrap src/Script/verifica_caracteristica.php teste/script/verifica_caracteristica_test.php
  - phpunit --bootstrap src/Script/cotacao_dolar.php teste/script/cotacao_dolar_test.php